FROM --platform=linux/arm64 php:8.4-cli

RUN apt-get update -qq \
    && apt-get install -y -qq git unzip libicu-dev libzip-dev > /dev/null 2>&1 \
    && docker-php-ext-install intl pdo pdo_mysql mysqli zip > /dev/null 2>&1 \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer > /dev/null 2>&1 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
